/**
 * Smart Contract ABIs (Unified Naming)
 * 
 * 命名策略：
 * - 文件名：统一无版本号（如 BLSAggregator.json）
 * - 版本信息：通过 ABI 中的 version() 函数获取
 * - 同步时自动去除版本号后缀（V3 等）
 */

// Core System
import RegistryABIData from './Registry.json' with { type: 'json' };
import GTokenABIData from './GToken.json' with { type: 'json' };
import GTokenAuthorizationABIData from './GTokenAuthorization.json' with { type: 'json' };
import GTokenStakingABIData from './GTokenStaking.json' with { type: 'json' };
import SuperPaymasterABIData from './SuperPaymaster.json' with { type: 'json' };
import PaymasterFactoryABIData from './PaymasterFactory.json' with { type: 'json' };
import PaymasterABIData from './Paymaster.json' with { type: 'json' };

// AA Standard (从 out/ 提取)
import EntryPointABIData from './EntryPoint.json' with { type: 'json' };
import SimpleAccountABIData from './SimpleAccount.json' with { type: 'json' };
import SimpleAccountFactoryABIData from './SimpleAccountFactory.json' with { type: 'json' };
// AirAccount V7 (diamond-lite) — MERGED full ABI: account + fallback-routed agent/weight
// functions. Generated by `scripts/build-full-abi.mjs` in airaccount-contract. Do NOT replace
// with the raw out/AAStarAirAccountV7.json ABI: agent (ERC-8004) + weight-governance functions
// execute via fallback->delegatecall and are absent from the raw account ABI. See contract repo
// docs/2026-05-26-diamond-lite-migration-impact.md.
import AAStarAirAccountV7ABIData from './AAStarAirAccountV7.json' with { type: 'json' };

// Token System
import xPNTsTokenABIData from './xPNTsToken.json' with { type: 'json' };
import xPNTsFactoryABIData from './xPNTsFactory.json' with { type: 'json' };
import MySBTABIData from './MySBT.json' with { type: 'json' };

// Agent Economy (SP V5.3)
import MicroPaymentChannelABIData from './MicroPaymentChannel.json' with { type: 'json' };

// Identity & Reputation
import ReputationSystemABIData from './ReputationSystem.json' with { type: 'json' };

// Monitoring System
import DVTValidatorABIData from './DVTValidator.json' with { type: 'json' };
import BLSAggregatorABIData from './BLSAggregator.json' with { type: 'json' };
import BLSValidatorABIData from './BLSValidator.json' with { type: 'json' };

// ========== Re-export ABIs - Core System ==========
export const RegistryABI = (RegistryABIData as any).abi || RegistryABIData;
export const RegistryArtifact = RegistryABIData;

export const GTokenABI = (GTokenABIData as any).abi || GTokenABIData;
export const GTokenArtifact = GTokenABIData;

// GTokenAuthorization v2.2.0 — EIP-3009 gasless transfers (SuperPaymaster main, 2026-05-21)
// @notice Requires GTokenAuthorization contract deployment. Do NOT use with legacy GToken address.
// @notice MAX_AUTH_VALIDITY = 5 min — keep validBefore - validAfter < 300s.
// @notice receiveWithAuthorization: msg.sender must equal `to` (relay cannot submit).
export const GTokenAuthorizationABI = (GTokenAuthorizationABIData as any).abi || GTokenAuthorizationABIData;
export const GTokenAuthorizationArtifact = GTokenAuthorizationABIData;

export const GTokenStakingABI = (GTokenStakingABIData as any).abi || GTokenStakingABIData;
export const GTokenStakingArtifact = GTokenStakingABIData;

export const SuperPaymasterABI = (SuperPaymasterABIData as any).abi || SuperPaymasterABIData;
export const SuperPaymasterArtifact = SuperPaymasterABIData;

export const PaymasterFactoryABI = (PaymasterFactoryABIData as any).abi || PaymasterFactoryABIData;
export const PaymasterFactoryArtifact = PaymasterFactoryABIData;

// Paymaster V4 (使用 Paymaster.json)
export const PaymasterABI = (PaymasterABIData as any).abi || PaymasterABIData;
export const PaymasterArtifact = PaymasterABIData;

// ========== AA Standard ==========
export const EntryPointABI = (EntryPointABIData as any).abi || EntryPointABIData;
export const EntryPointArtifact = EntryPointABIData;

export const SimpleAccountABI = (SimpleAccountABIData as any).abi || SimpleAccountABIData;
export const SimpleAccountArtifact = SimpleAccountABIData;

export const SimpleAccountFactoryABI = (SimpleAccountFactoryABIData as any).abi || SimpleAccountFactoryABIData;
export const SimpleAccountFactoryArtifact = SimpleAccountFactoryABIData;

// AirAccount V7 (diamond-lite). Full ABI includes the fallback-routed agent + weight-governance
// functions — call them at the ACCOUNT address; the account routes to AirAccountExtension internally.
export const AAStarAirAccountV7ABI = (AAStarAirAccountV7ABIData as any).abi || AAStarAirAccountV7ABIData;
export const AAStarAirAccountV7Artifact = AAStarAirAccountV7ABIData;

// ========== Token System ==========
export const xPNTsTokenABI = (xPNTsTokenABIData as any).abi || xPNTsTokenABIData;
export const xPNTsTokenArtifact = xPNTsTokenABIData;

export const xPNTsFactoryABI = (xPNTsFactoryABIData as any).abi || xPNTsFactoryABIData;
export const xPNTsFactoryArtifact = xPNTsFactoryABIData;

export const MySBTABI = (MySBTABIData as any).abi || MySBTABIData;
export const MySBTArtifact = MySBTABIData;

// ========== Agent Economy (SP V5.3) ==========
export const MicroPaymentChannelABI = (MicroPaymentChannelABIData as any).abi || MicroPaymentChannelABIData;
export const MicroPaymentChannelArtifact = MicroPaymentChannelABIData;

// ========== Identity & Reputation ==========
export const ReputationSystemABI = (ReputationSystemABIData as any).abi || ReputationSystemABIData;
export const ReputationSystemArtifact = ReputationSystemABIData;

// ========== Monitoring System ==========
export const DVTValidatorABI = (DVTValidatorABIData as any).abi || DVTValidatorABIData;
export const DVTValidatorArtifact = DVTValidatorABIData;

export const BLSAggregatorABI = (BLSAggregatorABIData as any).abi || BLSAggregatorABIData;
export const BLSAggregatorArtifact = BLSAggregatorABIData;

export const BLSValidatorABI = (BLSValidatorABIData as any).abi || BLSValidatorABIData;
export const BLSValidatorArtifact = BLSValidatorABIData;


// ========== AirAccount v0.17.2-beta.3 stack (synced 2026-06-12) ==========
//
// Source: github.com/AAStarCommunity/airaccount-contract tag `v0.17.2-beta.3`.
// Generated via `forge build` artifacts; AAStarAirAccountV7 is the merged-full ABI
// (account + fallback-routed agent/weight, 146 entries) — already imported above.
//
// Sepolia deployment 2026-06-12:
//   AAStarBLSAlgorithm        0xB82127182A855B82eED05e47536FcE568b626457  (unchanged)
//   AAStarValidator (router)  0x3c2b06f50300912794f29de031b33dd37bb8d6c6  (NEW — M3 timelock, finalized)
//   AAStarBLSAggregator       0xBAc3f24946d0eb15189E1c01e38182e5B078Bbc1  (unchanged)
//   SessionKeyValidator       0x655ca2e9a2d1178f7fbcea1856560d1e0c657ebf  (NEW — MODULE_VERSION + P256)
//   ForceExitModule           0xdb396ca2dc279f9bcb95fa3d8275f77c9f0c8702  (NEW — IncompatibleAccount error)
//   AirAccountDelegate        0x8603AAF6C3f07fdae810B323c95a198D796EC52E  (unchanged)
//   CalldataParserRegistry    0x076EE45d2a97F70FCb2e45809DC5f9b72BB4883F  (unchanged)
//   AAStarAirAccountFactoryV7 0xfc6234bbd6283610659211347c6309904be86b0a  (NEW — custom errors + FACTORY_VERSION)
//   AAStarAirAccountV7 (impl) 0xe33EeCF21AAC2B776b49A4dd52BA8b7e683dE9C3  (NEW — ACCOUNT_VERSION)
//   AirAccountExtension       0xB3c7312bA52dF306DE1cBa781B91f3AfA7e86F99  (NEW — _popcount asm)
//   AgentRegistry             0x9e8f576cad8a8f949181fd10d9ad1c49a7b0bc17  (NEW — bindFactory wired)
//
// NOTE on naming overlap with SuperPaymaster: this repo has BOTH
//   - BLSAggregator.json + BLSValidator.json (legacy SuperPaymaster exports above)
//   - AAStarBLSAggregator.json + AAStarBLSAlgorithm.json (THIS section — AirAccount v0.17.2)
// They are NOT the same — AirAccount uses EIP-2537 BLS12-381 pairing primitives.

import AAStarAirAccountFactoryV7ABIData from './AAStarAirAccountFactoryV7.json' with { type: 'json' };
import AgentRegistryABIData from './AgentRegistry.json' with { type: 'json' };
import SessionKeyValidatorABIData from './SessionKeyValidator.json' with { type: 'json' };
import ForceExitModuleABIData from './ForceExitModule.json' with { type: 'json' };
import AirAccountDelegateABIData from './AirAccountDelegate.json' with { type: 'json' };
import AAStarValidatorABIData from './AAStarValidator.json' with { type: 'json' };
import AAStarBLSAlgorithmABIData from './AAStarBLSAlgorithm.json' with { type: 'json' };
import AAStarBLSAggregatorABIData from './AAStarBLSAggregator.json' with { type: 'json' };
import CalldataParserRegistryABIData from './CalldataParserRegistry.json' with { type: 'json' };
import AirAccountExtensionABIData from './AirAccountExtension.json' with { type: 'json' };

export const AAStarAirAccountFactoryV7ABI = (AAStarAirAccountFactoryV7ABIData as any).abi || AAStarAirAccountFactoryV7ABIData;
export const AAStarAirAccountFactoryV7Artifact = AAStarAirAccountFactoryV7ABIData;

export const AgentRegistryABI = (AgentRegistryABIData as any).abi || AgentRegistryABIData;
export const AgentRegistryArtifact = AgentRegistryABIData;

// v0.17.2-beta.1 unified Session Key (algId 0x08) — replaces deleted AgentSessionKeyValidator +
// AirAccountCompositeValidator + TierGuardHook. Carries both classic single-target sessions and
// agent-grade controls (velocity, callTargets[], selectorAllowlist[]). 19 functions.
export const SessionKeyValidatorABI = (SessionKeyValidatorABIData as any).abi || SessionKeyValidatorABIData;
export const SessionKeyValidatorArtifact = SessionKeyValidatorABIData;

// v0.17.2-beta.3 ForceExitModule — IncompatibleAccount error + assembly _countBits + MODULE_VERSION.
// Per-account ERC-7579 Executor (moduleTypeId=2). Errors: SignerNoLongerGuardian, IncompatibleAccount.
export const ForceExitModuleABI = (ForceExitModuleABIData as any).abi || ForceExitModuleABIData;
export const ForceExitModuleArtifact = ForceExitModuleABIData;

// EIP-7702 delegation target — turns a regular EOA into an AirAccount-managed wallet.
export const AirAccountDelegateABI = (AirAccountDelegateABIData as any).abi || AirAccountDelegateABIData;
export const AirAccountDelegateArtifact = AirAccountDelegateABIData;

// AAStar validator router — algId → algorithm-contract dispatch. NOT the same as
// SuperPaymaster's BLSValidator.json above.
export const AAStarValidatorABI = (AAStarValidatorABIData as any).abi || AAStarValidatorABIData;
export const AAStarValidatorArtifact = AAStarValidatorABIData;

// AirAccount BLS primitives (EIP-2537 pairing). NOT the same as SuperPaymaster's
// BLSAggregator.json / BLSValidator.json above.
export const AAStarBLSAlgorithmABI = (AAStarBLSAlgorithmABIData as any).abi || AAStarBLSAlgorithmABIData;
export const AAStarBLSAlgorithmArtifact = AAStarBLSAlgorithmABIData;

export const AAStarBLSAggregatorABI = (AAStarBLSAggregatorABIData as any).abi || AAStarBLSAggregatorABIData;
export const AAStarBLSAggregatorArtifact = AAStarBLSAggregatorABIData;

// DeFi calldata parser registry — parsers OPT-IN per account via account.setParserRegistry.
// v0.17.2-beta.1 KI-14: Railgun + Uniswap parser NOT deployed (fail-open bug); only the
// registry stub is on-chain.
export const CalldataParserRegistryABI = (CalldataParserRegistryABIData as any).abi || CalldataParserRegistryABIData;
export const CalldataParserRegistryArtifact = CalldataParserRegistryABIData;

// Diamond-lite fallback target for AAStarAirAccountV7 — agent (ERC-8004) + weighted-signature
// governance. Reached via account's fallback->delegatecall. Standalone ABI included for tooling
// that wants to encode calls without going through the merged V7 ABI.
export const AirAccountExtensionABI = (AirAccountExtensionABIData as any).abi || AirAccountExtensionABIData;
export const AirAccountExtensionArtifact = AirAccountExtensionABIData;
