/**
 * Quick Test Account Setup - Generate ONE account to avoid nonce conflicts
 */
import { createPublicClient, createWalletClient, http, parseEther } from 'viem';
import { generatePrivateKey, privateKeyToAccount } from 'viem/accounts';
import { getNetworkConfig } from './00_utils.js';
import * as dotenv from 'dotenv';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as fs from 'fs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.resolve(__dirname, '../.env.sepolia') });

async function main() {
    console.log('🚀 Quick Setup: Generating Test Account A using SDK API...\n');

    const { chain, rpc } = getNetworkConfig('sepolia');
    const deployerKey = (process.env.PRIVATE_KEY_JASON || process.env.ADMIN_KEY) as `0x${string}`;
    
    if (!deployerKey) {
        throw new Error('Missing PRIVATE_KEY_JASON or ADMIN_KEY');
    }

    const deployerAccount = privateKeyToAccount(deployerKey);
    const publicClient = createPublicClient({ chain, transport: http(rpc) });
    const deployerWallet = createWalletClient({ account: deployerAccount, chain, transport: http(rpc) });
    
    // Use SDK API
    const { TestAccountManager } = await import('../packages/enduser/src/index.js');
    const toolkit = new TestAccountManager(publicClient, deployerWallet);
    
    // Generate ONLY 1 account to avoid nonce issues
    console.log('📝 Generating Account A...\n');
    const ownerKey = generatePrivateKey();
    const ownerAccount = privateKeyToAccount(ownerKey);
    console.log(`🔑 Owner EOA: ${ownerAccount.address}`);
    
    // Deploy AA
    console.log(`🏭 Deploying SimpleAccount...`);
    const { EndUserClient } = await import('../packages/enduser/src/index.js');
    const endUser = new EndUserClient(publicClient, deployerWallet);
    
    const { accountAddress, deployTxHash } = await endUser.deploySmartAccount({
        owner: ownerAccount.address,
        salt: 0n,
        fundWithETH: parseEther("0.02")
    });
    
    console.log(`✅ AA: ${accountAddress}`);
    console.log(`📝 Tx: https://sepolia.etherscan.io/tx/${deployTxHash}`);
    
    // Fund EOA
    console.log(`\n⛽ Funding EOA...`);
    const fundTx = await deployerWallet.sendTransaction({
        to: ownerAccount.address,
        value: parseEther("0.01")
    });
    await publicClient.waitForTransactionReceipt({ hash: fundTx });
    console.log(`✅ EOA Funded`);
    
    // Save to .env
    const envContent = `
# Test Account A (Generated by TestAccountManager)
TEST_OWNER_KEY_A=${ownerKey}
TEST_OWNER_EOA_A=${ownerAccount.address}
TEST_SIMPLE_ACCOUNT_A=${accountAddress}
`;
    
    const envPath = path.resolve(__dirname, '../.env.sepolia');
    fs.appendFileSync(envPath, envContent);
    console.log(`\n✅ Saved to .env.sepolia`);
    console.log(`\n📊 Account A Ready:`);
    console.log(`   EOA: ${ownerAccount.address}`);
    console.log(`   AA:  ${accountAddress}`);
}

main().catch(console.error);
